# ===================================
#  Relation Behavior Config
# ===================================

availabledates:
    label: Course available dates for reservations
    list: ~/plugins/logingrupa/studybook/models/availabledate/columns.yaml
    form: ~/plugins/logingrupa/studybook/models/availabledate/fields_simple.yaml
    readOnly: true

    view:
        label: test
        filter: config_availabledates_filter.yaml
        showSearch: false
        toolbarButtons: create|unlink|link
        showCheckboxes: true
    customMessages:
        buttonCreate: 'logingrupa.studybook::lang.button.add'
        buttonLink: 'logingrupa.studybook::lang.button.link'
        buttonUnlink: 'logingrupa.studybook::lang.button.unlink'
        titleAddForm: tests
        titleCreateForm: 'logingrupa.studybook::lang.availabledate.titleCreateForm'
        titleLinkForm: 'logingrupa.studybook::lang.availabledate.titleLinkForm'
        confirmUnlink: 'logingrupa.studybook::lang.availabledate.confirmUnlink'
        flashUnlink: 'logingrupa.studybook::lang.availabledate.flashUnlink'
    manage:
        context: relation
        recordsPerPage: 10
        showSearch: false
        showCheckboxes: true
        toolbarButtons: create|unlink|link
