# Record name
name: 'logingrupa.studybook::lang.availabledate.name'

# Model Form Field configuration
form: $/logingrupa/studybook/models/availabledate/fields.yaml

# Model Class name
modelClass: Logingrupa\Studybook\Models\AvailableDate

# Default redirect location
defaultRedirect: logingrupa/studybook/availabledates

# Create page
create:
    title: 'backend::lang.form.create_title'
    redirect: logingrupa/studybook/availabledates/update/:id
    redirectClose: logingrupa/studybook/availabledates
    flashSave: 'lovata.toolbox::lang.message.create_success'

# Update page
update:
    title: 'backend::lang.form.update_title'
    redirect: logingrupa/studybook/availabledates
    redirectClose: logingrupa/studybook/availabledates
    flashSave: 'lovata.toolbox::lang.message.update_success'
    flashDelete: 'lovata.toolbox::lang.message.delete_success'

# Import page
import:
    title: 'backend::lang.form.update_title'
    redirect: logingrupa/studybook/availabledates/import
    redirectClose: logingrupa/studybook/emails

# Preview page
preview: {  }
