scopes:
    excludeExpiredDates:
        label: 'logingrupa.studybook::lang.availabledate.excludeExpiredDates'
        scope: excludeExpiredDates
        modelClass: Logingrupa\Studybook\Models\AvailableDate
        nameFrom: datetime
        type: checkbox
        default: 1
    start_at:
        label: 'logingrupa.studybook::lang.field.start_at'
        modelClass: Logingrupa\Studybook\Models\Reservation
        type: group
        conditions: start_at in (:filtered)
        options: listReservationDates
    course:
        label: 'logingrupa.studybook::lang.course.name'
        modelClass: Logingrupa\Studybook\Models\Course
        conditions: course_id in (:filtered)
        nameFrom: name
    attendance:
        label: 'logingrupa.studybook::lang.field.attendance'
        type: switch
        conditions:
            - attendance = 0
            - attendance = 1
    student_health:
        label: 'logingrupa.studybook::lang.field.health'
        type: switch
        conditions:
            - health = 0
            - health = 1
#    start_at:
#        label: 'logingrupa.studybook::lang.field.start_at'
#        type: date
#        conditions: start_at >= ':after' AND start_at <= ':before'
